/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = com.ultracart.admin.v2.Client.SwaggerDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// CouponTierQuantity
    /// </summary>
    [DataContract]
    public partial class CouponTierQuantity :  IEquatable<CouponTierQuantity>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CouponTierQuantity" /> class.
        /// </summary>
        /// <param name="DiscountAmount">The amount of discount per item..</param>
        /// <param name="ItemQuantity">The quantity of item purchased (in units).</param>
        public CouponTierQuantity(decimal? DiscountAmount = default(decimal?), int? ItemQuantity = default(int?))
        {
            this.DiscountAmount = DiscountAmount;
            this.ItemQuantity = ItemQuantity;
        }
        
        /// <summary>
        /// The amount of discount per item.
        /// </summary>
        /// <value>The amount of discount per item.</value>
        [DataMember(Name="discount_amount", EmitDefaultValue=false)]
        public decimal? DiscountAmount { get; set; }

        /// <summary>
        /// The quantity of item purchased (in units)
        /// </summary>
        /// <value>The quantity of item purchased (in units)</value>
        [DataMember(Name="item_quantity", EmitDefaultValue=false)]
        public int? ItemQuantity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CouponTierQuantity {\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  ItemQuantity: ").Append(ItemQuantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CouponTierQuantity);
        }

        /// <summary>
        /// Returns true if CouponTierQuantity instances are equal
        /// </summary>
        /// <param name="input">Instance of CouponTierQuantity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CouponTierQuantity input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DiscountAmount == input.DiscountAmount ||
                    (this.DiscountAmount != null &&
                    this.DiscountAmount.Equals(input.DiscountAmount))
                ) && 
                (
                    this.ItemQuantity == input.ItemQuantity ||
                    (this.ItemQuantity != null &&
                    this.ItemQuantity.Equals(input.ItemQuantity))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DiscountAmount != null)
                    hashCode = hashCode * 59 + this.DiscountAmount.GetHashCode();
                if (this.ItemQuantity != null)
                    hashCode = hashCode * 59 + this.ItemQuantity.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
