/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = com.ultracart.admin.v2.Client.SwaggerDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// ItemShippingPackageRequirement
    /// </summary>
    [DataContract]
    public partial class ItemShippingPackageRequirement :  IEquatable<ItemShippingPackageRequirement>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemShippingPackageRequirement" /> class.
        /// </summary>
        /// <param name="PackageName">Package name.</param>
        /// <param name="PackageOid">Package object identifier.</param>
        public ItemShippingPackageRequirement(string PackageName = default(string), int? PackageOid = default(int?))
        {
            this.PackageName = PackageName;
            this.PackageOid = PackageOid;
        }
        
        /// <summary>
        /// Package name
        /// </summary>
        /// <value>Package name</value>
        [DataMember(Name="package_name", EmitDefaultValue=false)]
        public string PackageName { get; set; }

        /// <summary>
        /// Package object identifier
        /// </summary>
        /// <value>Package object identifier</value>
        [DataMember(Name="package_oid", EmitDefaultValue=false)]
        public int? PackageOid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemShippingPackageRequirement {\n");
            sb.Append("  PackageName: ").Append(PackageName).Append("\n");
            sb.Append("  PackageOid: ").Append(PackageOid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ItemShippingPackageRequirement);
        }

        /// <summary>
        /// Returns true if ItemShippingPackageRequirement instances are equal
        /// </summary>
        /// <param name="input">Instance of ItemShippingPackageRequirement to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemShippingPackageRequirement input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PackageName == input.PackageName ||
                    (this.PackageName != null &&
                    this.PackageName.Equals(input.PackageName))
                ) && 
                (
                    this.PackageOid == input.PackageOid ||
                    (this.PackageOid != null &&
                    this.PackageOid.Equals(input.PackageOid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PackageName != null)
                    hashCode = hashCode * 59 + this.PackageName.GetHashCode();
                if (this.PackageOid != null)
                    hashCode = hashCode * 59 + this.PackageOid.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
