/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using com.ultracart.admin.v2.Client;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing AutoOrderApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AutoOrderApiTests
    {
        private AutoOrderApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AutoOrderApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AutoOrderApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AutoOrderApi
            //Assert.IsInstanceOfType(typeof(AutoOrderApi), instance, "instance is a AutoOrderApi");
        }

        
        /// <summary>
        /// Test GetAutoOrder
        /// </summary>
        [Test]
        public void GetAutoOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? autoOrderOid = null;
            //string expand = null;
            //var response = instance.GetAutoOrder(autoOrderOid, expand);
            //Assert.IsInstanceOf<AutoOrderResponse> (response, "response is AutoOrderResponse");
        }
        
        /// <summary>
        /// Test GetAutoOrderByCode
        /// </summary>
        [Test]
        public void GetAutoOrderByCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string autoOrderCode = null;
            //string expand = null;
            //var response = instance.GetAutoOrderByCode(autoOrderCode, expand);
            //Assert.IsInstanceOf<AutoOrderResponse> (response, "response is AutoOrderResponse");
        }
        
        /// <summary>
        /// Test GetAutoOrderByReferenceOrderId
        /// </summary>
        [Test]
        public void GetAutoOrderByReferenceOrderIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string referenceOrderId = null;
            //string expand = null;
            //var response = instance.GetAutoOrderByReferenceOrderId(referenceOrderId, expand);
            //Assert.IsInstanceOf<AutoOrderResponse> (response, "response is AutoOrderResponse");
        }
        
        /// <summary>
        /// Test GetAutoOrders
        /// </summary>
        [Test]
        public void GetAutoOrdersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string autoOrderCode = null;
            //string originalOrderId = null;
            //string firstName = null;
            //string lastName = null;
            //string company = null;
            //string city = null;
            //string state = null;
            //string postalCode = null;
            //string countryCode = null;
            //string phone = null;
            //string email = null;
            //string originalOrderDateBegin = null;
            //string originalOrderDateEnd = null;
            //string nextShipmentDateBegin = null;
            //string nextShipmentDateEnd = null;
            //string cardType = null;
            //string itemId = null;
            //string status = null;
            //int? limit = null;
            //int? offset = null;
            //string since = null;
            //string sort = null;
            //string expand = null;
            //var response = instance.GetAutoOrders(autoOrderCode, originalOrderId, firstName, lastName, company, city, state, postalCode, countryCode, phone, email, originalOrderDateBegin, originalOrderDateEnd, nextShipmentDateBegin, nextShipmentDateEnd, cardType, itemId, status, limit, offset, since, sort, expand);
            //Assert.IsInstanceOf<AutoOrdersResponse> (response, "response is AutoOrdersResponse");
        }
        
        /// <summary>
        /// Test UpdateAutoOrder
        /// </summary>
        [Test]
        public void UpdateAutoOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AutoOrder autoOrder = null;
            //int? autoOrderOid = null;
            //string expand = null;
            //var response = instance.UpdateAutoOrder(autoOrder, autoOrderOid, expand);
            //Assert.IsInstanceOf<AutoOrderResponse> (response, "response is AutoOrderResponse");
        }
        
    }

}
