using System;
using System.Web;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using RestSharp;

namespace SdkSample.checkout
{
    public class GetCartByReturnCode
    {
        /// <summary>
        /// Retrieves a cart using a return code
        /// </summary>
        public static void Execute()
        {
            // Reference Implementation: https://github.com/UltraCart/responsive_checkout

            // this example returns a shopping cart given a return_code.  The return_code is generated by UltraCart
            // and usually emailed to a customer.  The email will provide a link to this script where you may use the
            // return_code to retrieve the customer's cart.

            CheckoutApi checkoutApi = new CheckoutApi(Constants.ApiKey);

            String expansion = "items,billing,shipping,coupons,checkout,payment,summary,taxes"; //
            // Possible Expansion Variables: (see https://www.ultracart.com/api/#resource_checkout.html
            /*
            affiliate                   checkout                            customer_profile
            billing                     coupons                             gift
            gift_certificate            items.attributes                   items.multimedia
            items                       items.multimedia.thumbnails         items.physical
            marketing                   payment                                settings.gift
            settings.billing.provinces  settings.shipping.deliver_on_date   settings.shipping.estimates
            settings.shipping.provinces settings.shipping.ship_on_date     settings.taxes
            settings.terms              shipping                           taxes
            summary                     upsell_after
             */

            String returnCode = "1234567890"; // usually retrieved from a query parameter
            CartResponse apiResponse = checkoutApi.GetCartByReturnCode(returnCode, expansion);
            Cart cart = apiResponse.Cart;

            // TODO: set or re-set the cart cookie if this is part of a multi-page process. two weeks is a generous cart id time.
            HttpCookie cookie = new HttpCookie(Constants.CartIdCookieName);
            cookie.Value = cart.CartId;
            cookie.Expires = DateTime.Now.AddDays(14); // 1209600 seconds = 14 days
            cookie.Path = "/";
            // HttpContext.Current.Response.Cookies.Add(cookie);

            Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(cart, Newtonsoft.Json.Formatting.Indented));
        }
    }
}