/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing AutoOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AutoOrderTests
    {
        // TODO uncomment below to declare an instance variable for AutoOrder
        //private AutoOrder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AutoOrder
            //instance = new AutoOrder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AutoOrder
        /// </summary>
        [Test]
        public void AutoOrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AutoOrder
            //Assert.IsInstanceOfType<AutoOrder> (instance, "variable 'instance' is a AutoOrder");
        }


        /// <summary>
        /// Test the property 'AutoOrderCode'
        /// </summary>
        [Test]
        public void AutoOrderCodeTest()
        {
            // TODO unit test for the property 'AutoOrderCode'
        }
        /// <summary>
        /// Test the property 'AutoOrderOid'
        /// </summary>
        [Test]
        public void AutoOrderOidTest()
        {
            // TODO unit test for the property 'AutoOrderOid'
        }
        /// <summary>
        /// Test the property 'CancelAfterNextXOrders'
        /// </summary>
        [Test]
        public void CancelAfterNextXOrdersTest()
        {
            // TODO unit test for the property 'CancelAfterNextXOrders'
        }
        /// <summary>
        /// Test the property 'CancelDowngrade'
        /// </summary>
        [Test]
        public void CancelDowngradeTest()
        {
            // TODO unit test for the property 'CancelDowngrade'
        }
        /// <summary>
        /// Test the property 'CancelUpgrade'
        /// </summary>
        [Test]
        public void CancelUpgradeTest()
        {
            // TODO unit test for the property 'CancelUpgrade'
        }
        /// <summary>
        /// Test the property 'CanceledByUser'
        /// </summary>
        [Test]
        public void CanceledByUserTest()
        {
            // TODO unit test for the property 'CanceledByUser'
        }
        /// <summary>
        /// Test the property 'CanceledDts'
        /// </summary>
        [Test]
        public void CanceledDtsTest()
        {
            // TODO unit test for the property 'CanceledDts'
        }
        /// <summary>
        /// Test the property 'CreditCardAttempt'
        /// </summary>
        [Test]
        public void CreditCardAttemptTest()
        {
            // TODO unit test for the property 'CreditCardAttempt'
        }
        /// <summary>
        /// Test the property 'DisabledDts'
        /// </summary>
        [Test]
        public void DisabledDtsTest()
        {
            // TODO unit test for the property 'DisabledDts'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'FailureReason'
        /// </summary>
        [Test]
        public void FailureReasonTest()
        {
            // TODO unit test for the property 'FailureReason'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'NextAttempt'
        /// </summary>
        [Test]
        public void NextAttemptTest()
        {
            // TODO unit test for the property 'NextAttempt'
        }
        /// <summary>
        /// Test the property 'OriginalOrder'
        /// </summary>
        [Test]
        public void OriginalOrderTest()
        {
            // TODO unit test for the property 'OriginalOrder'
        }
        /// <summary>
        /// Test the property 'OriginalOrderId'
        /// </summary>
        [Test]
        public void OriginalOrderIdTest()
        {
            // TODO unit test for the property 'OriginalOrderId'
        }
        /// <summary>
        /// Test the property 'OverrideAffiliateId'
        /// </summary>
        [Test]
        public void OverrideAffiliateIdTest()
        {
            // TODO unit test for the property 'OverrideAffiliateId'
        }
        /// <summary>
        /// Test the property 'RebillOrders'
        /// </summary>
        [Test]
        public void RebillOrdersTest()
        {
            // TODO unit test for the property 'RebillOrders'
        }
        /// <summary>
        /// Test the property 'RotatingTransactionGatewayCode'
        /// </summary>
        [Test]
        public void RotatingTransactionGatewayCodeTest()
        {
            // TODO unit test for the property 'RotatingTransactionGatewayCode'
        }

    }

}
