/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CartSettingsShipping
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartSettingsShippingTests
    {
        // TODO uncomment below to declare an instance variable for CartSettingsShipping
        //private CartSettingsShipping instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CartSettingsShipping
            //instance = new CartSettingsShipping();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartSettingsShipping
        /// </summary>
        [Test]
        public void CartSettingsShippingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CartSettingsShipping
            //Assert.IsInstanceOfType<CartSettingsShipping> (instance, "variable 'instance' is a CartSettingsShipping");
        }


        /// <summary>
        /// Test the property 'DeliverOnDate'
        /// </summary>
        [Test]
        public void DeliverOnDateTest()
        {
            // TODO unit test for the property 'DeliverOnDate'
        }
        /// <summary>
        /// Test the property 'Estimates'
        /// </summary>
        [Test]
        public void EstimatesTest()
        {
            // TODO unit test for the property 'Estimates'
        }
        /// <summary>
        /// Test the property 'NeedShipping'
        /// </summary>
        [Test]
        public void NeedShippingTest()
        {
            // TODO unit test for the property 'NeedShipping'
        }
        /// <summary>
        /// Test the property 'Provinces'
        /// </summary>
        [Test]
        public void ProvincesTest()
        {
            // TODO unit test for the property 'Provinces'
        }
        /// <summary>
        /// Test the property 'ShipOnDate'
        /// </summary>
        [Test]
        public void ShipOnDateTest()
        {
            // TODO unit test for the property 'ShipOnDate'
        }

    }

}
