/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CartGiftCertificate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartGiftCertificateTests
    {
        // TODO uncomment below to declare an instance variable for CartGiftCertificate
        //private CartGiftCertificate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CartGiftCertificate
            //instance = new CartGiftCertificate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartGiftCertificate
        /// </summary>
        [Test]
        public void CartGiftCertificateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CartGiftCertificate
            //Assert.IsInstanceOfType<CartGiftCertificate> (instance, "variable 'instance' is a CartGiftCertificate");
        }


        /// <summary>
        /// Test the property 'GiftCertificateAmount'
        /// </summary>
        [Test]
        public void GiftCertificateAmountTest()
        {
            // TODO unit test for the property 'GiftCertificateAmount'
        }
        /// <summary>
        /// Test the property 'GiftCertificateCode'
        /// </summary>
        [Test]
        public void GiftCertificateCodeTest()
        {
            // TODO unit test for the property 'GiftCertificateCode'
        }
        /// <summary>
        /// Test the property 'GiftCertificateRemainingBalanceAfterOrder'
        /// </summary>
        [Test]
        public void GiftCertificateRemainingBalanceAfterOrderTest()
        {
            // TODO unit test for the property 'GiftCertificateRemainingBalanceAfterOrder'
        }

    }

}
