/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CartItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartItemTests
    {
        // TODO uncomment below to declare an instance variable for CartItem
        //private CartItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CartItem
            //instance = new CartItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartItem
        /// </summary>
        [Test]
        public void CartItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CartItem
            //Assert.IsInstanceOfType<CartItem> (instance, "variable 'instance' is a CartItem");
        }


        /// <summary>
        /// Test the property 'ArbitraryUnitCost'
        /// </summary>
        [Test]
        public void ArbitraryUnitCostTest()
        {
            // TODO unit test for the property 'ArbitraryUnitCost'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'AutoOrderSchedule'
        /// </summary>
        [Test]
        public void AutoOrderScheduleTest()
        {
            // TODO unit test for the property 'AutoOrderSchedule'
        }
        /// <summary>
        /// Test the property 'DefaultImageUrl'
        /// </summary>
        [Test]
        public void DefaultImageUrlTest()
        {
            // TODO unit test for the property 'DefaultImageUrl'
        }
        /// <summary>
        /// Test the property 'DefaultThumbnailUrl'
        /// </summary>
        [Test]
        public void DefaultThumbnailUrlTest()
        {
            // TODO unit test for the property 'DefaultThumbnailUrl'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Test]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'ExtendedDescription'
        /// </summary>
        [Test]
        public void ExtendedDescriptionTest()
        {
            // TODO unit test for the property 'ExtendedDescription'
        }
        /// <summary>
        /// Test the property 'ItemId'
        /// </summary>
        [Test]
        public void ItemIdTest()
        {
            // TODO unit test for the property 'ItemId'
        }
        /// <summary>
        /// Test the property 'ItemOid'
        /// </summary>
        [Test]
        public void ItemOidTest()
        {
            // TODO unit test for the property 'ItemOid'
        }
        /// <summary>
        /// Test the property 'Kit'
        /// </summary>
        [Test]
        public void KitTest()
        {
            // TODO unit test for the property 'Kit'
        }
        /// <summary>
        /// Test the property 'KitComponentOptions'
        /// </summary>
        [Test]
        public void KitComponentOptionsTest()
        {
            // TODO unit test for the property 'KitComponentOptions'
        }
        /// <summary>
        /// Test the property 'ManufacturerSuggestedRetailPrice'
        /// </summary>
        [Test]
        public void ManufacturerSuggestedRetailPriceTest()
        {
            // TODO unit test for the property 'ManufacturerSuggestedRetailPrice'
        }
        /// <summary>
        /// Test the property 'MaximumQuantity'
        /// </summary>
        [Test]
        public void MaximumQuantityTest()
        {
            // TODO unit test for the property 'MaximumQuantity'
        }
        /// <summary>
        /// Test the property 'MinimumQuantity'
        /// </summary>
        [Test]
        public void MinimumQuantityTest()
        {
            // TODO unit test for the property 'MinimumQuantity'
        }
        /// <summary>
        /// Test the property 'Multimedia'
        /// </summary>
        [Test]
        public void MultimediaTest()
        {
            // TODO unit test for the property 'Multimedia'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'Phsyical'
        /// </summary>
        [Test]
        public void PhsyicalTest()
        {
            // TODO unit test for the property 'Phsyical'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Preorder'
        /// </summary>
        [Test]
        public void PreorderTest()
        {
            // TODO unit test for the property 'Preorder'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Schedules'
        /// </summary>
        [Test]
        public void SchedulesTest()
        {
            // TODO unit test for the property 'Schedules'
        }
        /// <summary>
        /// Test the property 'TotalCost'
        /// </summary>
        [Test]
        public void TotalCostTest()
        {
            // TODO unit test for the property 'TotalCost'
        }
        /// <summary>
        /// Test the property 'TotalCostWithDiscount'
        /// </summary>
        [Test]
        public void TotalCostWithDiscountTest()
        {
            // TODO unit test for the property 'TotalCostWithDiscount'
        }
        /// <summary>
        /// Test the property 'UnitCost'
        /// </summary>
        [Test]
        public void UnitCostTest()
        {
            // TODO unit test for the property 'UnitCost'
        }
        /// <summary>
        /// Test the property 'UnitCostWithDiscount'
        /// </summary>
        [Test]
        public void UnitCostWithDiscountTest()
        {
            // TODO unit test for the property 'UnitCostWithDiscount'
        }
        /// <summary>
        /// Test the property 'Upsell'
        /// </summary>
        [Test]
        public void UpsellTest()
        {
            // TODO unit test for the property 'Upsell'
        }
        /// <summary>
        /// Test the property 'Variations'
        /// </summary>
        [Test]
        public void VariationsTest()
        {
            // TODO unit test for the property 'Variations'
        }
        /// <summary>
        /// Test the property 'ViewUrl'
        /// </summary>
        [Test]
        public void ViewUrlTest()
        {
            // TODO unit test for the property 'ViewUrl'
        }

    }

}
