/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CartPayment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartPaymentTests
    {
        // TODO uncomment below to declare an instance variable for CartPayment
        //private CartPayment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CartPayment
            //instance = new CartPayment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartPayment
        /// </summary>
        [Test]
        public void CartPaymentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CartPayment
            //Assert.IsInstanceOfType<CartPayment> (instance, "variable 'instance' is a CartPayment");
        }


        /// <summary>
        /// Test the property 'Amazon'
        /// </summary>
        [Test]
        public void AmazonTest()
        {
            // TODO unit test for the property 'Amazon'
        }
        /// <summary>
        /// Test the property 'Check'
        /// </summary>
        [Test]
        public void CheckTest()
        {
            // TODO unit test for the property 'Check'
        }
        /// <summary>
        /// Test the property 'CreditCard'
        /// </summary>
        [Test]
        public void CreditCardTest()
        {
            // TODO unit test for the property 'CreditCard'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Test]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'PurchaseOrder'
        /// </summary>
        [Test]
        public void PurchaseOrderTest()
        {
            // TODO unit test for the property 'PurchaseOrder'
        }
        /// <summary>
        /// Test the property 'RtgCode'
        /// </summary>
        [Test]
        public void RtgCodeTest()
        {
            // TODO unit test for the property 'RtgCode'
        }

    }

}
