/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CartSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartSummaryTests
    {
        // TODO uncomment below to declare an instance variable for CartSummary
        //private CartSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CartSummary
            //instance = new CartSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartSummary
        /// </summary>
        [Test]
        public void CartSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CartSummary
            //Assert.IsInstanceOfType<CartSummary> (instance, "variable 'instance' is a CartSummary");
        }


        /// <summary>
        /// Test the property 'ArbitraryShippingHandlingTotal'
        /// </summary>
        [Test]
        public void ArbitraryShippingHandlingTotalTest()
        {
            // TODO unit test for the property 'ArbitraryShippingHandlingTotal'
        }
        /// <summary>
        /// Test the property 'ArbitraryTax'
        /// </summary>
        [Test]
        public void ArbitraryTaxTest()
        {
            // TODO unit test for the property 'ArbitraryTax'
        }
        /// <summary>
        /// Test the property 'ArbitraryTaxRate'
        /// </summary>
        [Test]
        public void ArbitraryTaxRateTest()
        {
            // TODO unit test for the property 'ArbitraryTaxRate'
        }
        /// <summary>
        /// Test the property 'ArbitraryTaxableSubtotal'
        /// </summary>
        [Test]
        public void ArbitraryTaxableSubtotalTest()
        {
            // TODO unit test for the property 'ArbitraryTaxableSubtotal'
        }
        /// <summary>
        /// Test the property 'ShippingHandling'
        /// </summary>
        [Test]
        public void ShippingHandlingTest()
        {
            // TODO unit test for the property 'ShippingHandling'
        }
        /// <summary>
        /// Test the property 'ShippingHandlingDiscount'
        /// </summary>
        [Test]
        public void ShippingHandlingDiscountTest()
        {
            // TODO unit test for the property 'ShippingHandlingDiscount'
        }
        /// <summary>
        /// Test the property 'ShippingHandlingWithDiscount'
        /// </summary>
        [Test]
        public void ShippingHandlingWithDiscountTest()
        {
            // TODO unit test for the property 'ShippingHandlingWithDiscount'
        }
        /// <summary>
        /// Test the property 'Subtotal'
        /// </summary>
        [Test]
        public void SubtotalTest()
        {
            // TODO unit test for the property 'Subtotal'
        }
        /// <summary>
        /// Test the property 'SubtotalDiscount'
        /// </summary>
        [Test]
        public void SubtotalDiscountTest()
        {
            // TODO unit test for the property 'SubtotalDiscount'
        }
        /// <summary>
        /// Test the property 'SubtotalWithDiscount'
        /// </summary>
        [Test]
        public void SubtotalWithDiscountTest()
        {
            // TODO unit test for the property 'SubtotalWithDiscount'
        }
        /// <summary>
        /// Test the property 'Surcharge'
        /// </summary>
        [Test]
        public void SurchargeTest()
        {
            // TODO unit test for the property 'Surcharge'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Test]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }
        /// <summary>
        /// Test the property 'TaxableSubtotal'
        /// </summary>
        [Test]
        public void TaxableSubtotalTest()
        {
            // TODO unit test for the property 'TaxableSubtotal'
        }
        /// <summary>
        /// Test the property 'TaxableSubtotalDiscount'
        /// </summary>
        [Test]
        public void TaxableSubtotalDiscountTest()
        {
            // TODO unit test for the property 'TaxableSubtotalDiscount'
        }
        /// <summary>
        /// Test the property 'TaxableSubtotalWithDiscount'
        /// </summary>
        [Test]
        public void TaxableSubtotalWithDiscountTest()
        {
            // TODO unit test for the property 'TaxableSubtotalWithDiscount'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
