/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CartPaymentCheck
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartPaymentCheckTests
    {
        // TODO uncomment below to declare an instance variable for CartPaymentCheck
        //private CartPaymentCheck instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CartPaymentCheck
            //instance = new CartPaymentCheck();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartPaymentCheck
        /// </summary>
        [Test]
        public void CartPaymentCheckInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CartPaymentCheck
            //Assert.IsInstanceOfType<CartPaymentCheck> (instance, "variable 'instance' is a CartPaymentCheck");
        }


        /// <summary>
        /// Test the property 'CheckNumber'
        /// </summary>
        [Test]
        public void CheckNumberTest()
        {
            // TODO unit test for the property 'CheckNumber'
        }

    }

}
