/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CheckoutSetupBrowserKeyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CheckoutSetupBrowserKeyRequestTests
    {
        // TODO uncomment below to declare an instance variable for CheckoutSetupBrowserKeyRequest
        //private CheckoutSetupBrowserKeyRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CheckoutSetupBrowserKeyRequest
            //instance = new CheckoutSetupBrowserKeyRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CheckoutSetupBrowserKeyRequest
        /// </summary>
        [Test]
        public void CheckoutSetupBrowserKeyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CheckoutSetupBrowserKeyRequest
            //Assert.IsInstanceOfType<CheckoutSetupBrowserKeyRequest> (instance, "variable 'instance' is a CheckoutSetupBrowserKeyRequest");
        }


        /// <summary>
        /// Test the property 'AllowedReferrers'
        /// </summary>
        [Test]
        public void AllowedReferrersTest()
        {
            // TODO unit test for the property 'AllowedReferrers'
        }

    }

}
