/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CouponTieredAmountOffSubtotal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CouponTieredAmountOffSubtotalTests
    {
        // TODO uncomment below to declare an instance variable for CouponTieredAmountOffSubtotal
        //private CouponTieredAmountOffSubtotal instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CouponTieredAmountOffSubtotal
            //instance = new CouponTieredAmountOffSubtotal();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CouponTieredAmountOffSubtotal
        /// </summary>
        [Test]
        public void CouponTieredAmountOffSubtotalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CouponTieredAmountOffSubtotal
            //Assert.IsInstanceOfType<CouponTieredAmountOffSubtotal> (instance, "variable 'instance' is a CouponTieredAmountOffSubtotal");
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'Tiers'
        /// </summary>
        [Test]
        public void TiersTest()
        {
            // TODO unit test for the property 'Tiers'
        }

    }

}
