/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CouponFreeItemsWithItemPurchase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CouponFreeItemsWithItemPurchaseTests
    {
        // TODO uncomment below to declare an instance variable for CouponFreeItemsWithItemPurchase
        //private CouponFreeItemsWithItemPurchase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CouponFreeItemsWithItemPurchase
            //instance = new CouponFreeItemsWithItemPurchase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CouponFreeItemsWithItemPurchase
        /// </summary>
        [Test]
        public void CouponFreeItemsWithItemPurchaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CouponFreeItemsWithItemPurchase
            //Assert.IsInstanceOfType<CouponFreeItemsWithItemPurchase> (instance, "variable 'instance' is a CouponFreeItemsWithItemPurchase");
        }


        /// <summary>
        /// Test the property 'FreeItem'
        /// </summary>
        [Test]
        public void FreeItemTest()
        {
            // TODO unit test for the property 'FreeItem'
        }
        /// <summary>
        /// Test the property 'FreeQuantity'
        /// </summary>
        [Test]
        public void FreeQuantityTest()
        {
            // TODO unit test for the property 'FreeQuantity'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'RequiredPurchaseItem'
        /// </summary>
        [Test]
        public void RequiredPurchaseItemTest()
        {
            // TODO unit test for the property 'RequiredPurchaseItem'
        }
        /// <summary>
        /// Test the property 'RequiredPurchaseQuantity'
        /// </summary>
        [Test]
        public void RequiredPurchaseQuantityTest()
        {
            // TODO unit test for the property 'RequiredPurchaseQuantity'
        }

    }

}
