/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CouponPercentOffRetailPriceItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CouponPercentOffRetailPriceItemsTests
    {
        // TODO uncomment below to declare an instance variable for CouponPercentOffRetailPriceItems
        //private CouponPercentOffRetailPriceItems instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CouponPercentOffRetailPriceItems
            //instance = new CouponPercentOffRetailPriceItems();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CouponPercentOffRetailPriceItems
        /// </summary>
        [Test]
        public void CouponPercentOffRetailPriceItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CouponPercentOffRetailPriceItems
            //Assert.IsInstanceOfType<CouponPercentOffRetailPriceItems> (instance, "variable 'instance' is a CouponPercentOffRetailPriceItems");
        }


        /// <summary>
        /// Test the property 'DiscountPercent'
        /// </summary>
        [Test]
        public void DiscountPercentTest()
        {
            // TODO unit test for the property 'DiscountPercent'
        }
        /// <summary>
        /// Test the property 'ExcludedItems'
        /// </summary>
        [Test]
        public void ExcludedItemsTest()
        {
            // TODO unit test for the property 'ExcludedItems'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

    }

}
