/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CustomerAffiliate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomerAffiliateTests
    {
        // TODO uncomment below to declare an instance variable for CustomerAffiliate
        //private CustomerAffiliate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomerAffiliate
            //instance = new CustomerAffiliate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomerAffiliate
        /// </summary>
        [Test]
        public void CustomerAffiliateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomerAffiliate
            //Assert.IsInstanceOfType<CustomerAffiliate> (instance, "variable 'instance' is a CustomerAffiliate");
        }


        /// <summary>
        /// Test the property 'AffiliateOid'
        /// </summary>
        [Test]
        public void AffiliateOidTest()
        {
            // TODO unit test for the property 'AffiliateOid'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
