/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CustomerBilling
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomerBillingTests
    {
        // TODO uncomment below to declare an instance variable for CustomerBilling
        //private CustomerBilling instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomerBilling
            //instance = new CustomerBilling();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomerBilling
        /// </summary>
        [Test]
        public void CustomerBillingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomerBilling
            //Assert.IsInstanceOfType<CustomerBilling> (instance, "variable 'instance' is a CustomerBilling");
        }


        /// <summary>
        /// Test the property 'Address1'
        /// </summary>
        [Test]
        public void Address1Test()
        {
            // TODO unit test for the property 'Address1'
        }
        /// <summary>
        /// Test the property 'Address2'
        /// </summary>
        [Test]
        public void Address2Test()
        {
            // TODO unit test for the property 'Address2'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'CustomerBillingOid'
        /// </summary>
        [Test]
        public void CustomerBillingOidTest()
        {
            // TODO unit test for the property 'CustomerBillingOid'
        }
        /// <summary>
        /// Test the property 'CustomerProfileOid'
        /// </summary>
        [Test]
        public void CustomerProfileOidTest()
        {
            // TODO unit test for the property 'CustomerProfileOid'
        }
        /// <summary>
        /// Test the property 'DayPhone'
        /// </summary>
        [Test]
        public void DayPhoneTest()
        {
            // TODO unit test for the property 'DayPhone'
        }
        /// <summary>
        /// Test the property 'DefaultBilling'
        /// </summary>
        [Test]
        public void DefaultBillingTest()
        {
            // TODO unit test for the property 'DefaultBilling'
        }
        /// <summary>
        /// Test the property 'EveningPhone'
        /// </summary>
        [Test]
        public void EveningPhoneTest()
        {
            // TODO unit test for the property 'EveningPhone'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'LastUsedDts'
        /// </summary>
        [Test]
        public void LastUsedDtsTest()
        {
            // TODO unit test for the property 'LastUsedDts'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'StateRegion'
        /// </summary>
        [Test]
        public void StateRegionTest()
        {
            // TODO unit test for the property 'StateRegion'
        }
        /// <summary>
        /// Test the property 'TaxCounty'
        /// </summary>
        [Test]
        public void TaxCountyTest()
        {
            // TODO unit test for the property 'TaxCounty'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
