/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing ItemTax
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemTaxTests
    {
        // TODO uncomment below to declare an instance variable for ItemTax
        //private ItemTax instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemTax
            //instance = new ItemTax();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemTax
        /// </summary>
        [Test]
        public void ItemTaxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemTax
            //Assert.IsInstanceOfType<ItemTax> (instance, "variable 'instance' is a ItemTax");
        }


        /// <summary>
        /// Test the property 'Exemptions'
        /// </summary>
        [Test]
        public void ExemptionsTest()
        {
            // TODO unit test for the property 'Exemptions'
        }
        /// <summary>
        /// Test the property 'TaxFree'
        /// </summary>
        [Test]
        public void TaxFreeTest()
        {
            // TODO unit test for the property 'TaxFree'
        }
        /// <summary>
        /// Test the property 'TaxableCost'
        /// </summary>
        [Test]
        public void TaxableCostTest()
        {
            // TODO unit test for the property 'TaxableCost'
        }

    }

}
