/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing ItemEnrollment123
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemEnrollment123Tests
    {
        // TODO uncomment below to declare an instance variable for ItemEnrollment123
        //private ItemEnrollment123 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemEnrollment123
            //instance = new ItemEnrollment123();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemEnrollment123
        /// </summary>
        [Test]
        public void ItemEnrollment123InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemEnrollment123
            //Assert.IsInstanceOfType<ItemEnrollment123> (instance, "variable 'instance' is a ItemEnrollment123");
        }


        /// <summary>
        /// Test the property 'Enrollment123ProductCode'
        /// </summary>
        [Test]
        public void Enrollment123ProductCodeTest()
        {
            // TODO unit test for the property 'Enrollment123ProductCode'
        }

    }

}
