/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing ItemKitDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemKitDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for ItemKitDefinition
        //private ItemKitDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemKitDefinition
            //instance = new ItemKitDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemKitDefinition
        /// </summary>
        [Test]
        public void ItemKitDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemKitDefinition
            //Assert.IsInstanceOfType<ItemKitDefinition> (instance, "variable 'instance' is a ItemKitDefinition");
        }


        /// <summary>
        /// Test the property 'Components'
        /// </summary>
        [Test]
        public void ComponentsTest()
        {
            // TODO unit test for the property 'Components'
        }

    }

}
