/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing ItemGoogleProductSearch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemGoogleProductSearchTests
    {
        // TODO uncomment below to declare an instance variable for ItemGoogleProductSearch
        //private ItemGoogleProductSearch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemGoogleProductSearch
            //instance = new ItemGoogleProductSearch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemGoogleProductSearch
        /// </summary>
        [Test]
        public void ItemGoogleProductSearchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemGoogleProductSearch
            //Assert.IsInstanceOfType<ItemGoogleProductSearch> (instance, "variable 'instance' is a ItemGoogleProductSearch");
        }


        /// <summary>
        /// Test the property 'AdwordsGrouping'
        /// </summary>
        [Test]
        public void AdwordsGroupingTest()
        {
            // TODO unit test for the property 'AdwordsGrouping'
        }
        /// <summary>
        /// Test the property 'AdwordsLabel1'
        /// </summary>
        [Test]
        public void AdwordsLabel1Test()
        {
            // TODO unit test for the property 'AdwordsLabel1'
        }
        /// <summary>
        /// Test the property 'AdwordsLabel2'
        /// </summary>
        [Test]
        public void AdwordsLabel2Test()
        {
            // TODO unit test for the property 'AdwordsLabel2'
        }
        /// <summary>
        /// Test the property 'AdwordsLabel3'
        /// </summary>
        [Test]
        public void AdwordsLabel3Test()
        {
            // TODO unit test for the property 'AdwordsLabel3'
        }
        /// <summary>
        /// Test the property 'AdwordsLabel4'
        /// </summary>
        [Test]
        public void AdwordsLabel4Test()
        {
            // TODO unit test for the property 'AdwordsLabel4'
        }
        /// <summary>
        /// Test the property 'AdwordsLabel5'
        /// </summary>
        [Test]
        public void AdwordsLabel5Test()
        {
            // TODO unit test for the property 'AdwordsLabel5'
        }
        /// <summary>
        /// Test the property 'AgeGroup'
        /// </summary>
        [Test]
        public void AgeGroupTest()
        {
            // TODO unit test for the property 'AgeGroup'
        }
        /// <summary>
        /// Test the property 'AvailableAtPhysicalStore'
        /// </summary>
        [Test]
        public void AvailableAtPhysicalStoreTest()
        {
            // TODO unit test for the property 'AvailableAtPhysicalStore'
        }
        /// <summary>
        /// Test the property 'BookAuthor'
        /// </summary>
        [Test]
        public void BookAuthorTest()
        {
            // TODO unit test for the property 'BookAuthor'
        }
        /// <summary>
        /// Test the property 'BookFormat'
        /// </summary>
        [Test]
        public void BookFormatTest()
        {
            // TODO unit test for the property 'BookFormat'
        }
        /// <summary>
        /// Test the property 'BookIsbn'
        /// </summary>
        [Test]
        public void BookIsbnTest()
        {
            // TODO unit test for the property 'BookIsbn'
        }
        /// <summary>
        /// Test the property 'BookPublisher'
        /// </summary>
        [Test]
        public void BookPublisherTest()
        {
            // TODO unit test for the property 'BookPublisher'
        }
        /// <summary>
        /// Test the property 'CategoryDescription'
        /// </summary>
        [Test]
        public void CategoryDescriptionTest()
        {
            // TODO unit test for the property 'CategoryDescription'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Test]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
        /// <summary>
        /// Test the property 'CustomLabel0'
        /// </summary>
        [Test]
        public void CustomLabel0Test()
        {
            // TODO unit test for the property 'CustomLabel0'
        }
        /// <summary>
        /// Test the property 'CustomLabel1'
        /// </summary>
        [Test]
        public void CustomLabel1Test()
        {
            // TODO unit test for the property 'CustomLabel1'
        }
        /// <summary>
        /// Test the property 'CustomLabel2'
        /// </summary>
        [Test]
        public void CustomLabel2Test()
        {
            // TODO unit test for the property 'CustomLabel2'
        }
        /// <summary>
        /// Test the property 'CustomLabel3'
        /// </summary>
        [Test]
        public void CustomLabel3Test()
        {
            // TODO unit test for the property 'CustomLabel3'
        }
        /// <summary>
        /// Test the property 'CustomLabel4'
        /// </summary>
        [Test]
        public void CustomLabel4Test()
        {
            // TODO unit test for the property 'CustomLabel4'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Test]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'GoogleProductCategory'
        /// </summary>
        [Test]
        public void GoogleProductCategoryTest()
        {
            // TODO unit test for the property 'GoogleProductCategory'
        }
        /// <summary>
        /// Test the property 'MusicArtist'
        /// </summary>
        [Test]
        public void MusicArtistTest()
        {
            // TODO unit test for the property 'MusicArtist'
        }
        /// <summary>
        /// Test the property 'MusicFormat'
        /// </summary>
        [Test]
        public void MusicFormatTest()
        {
            // TODO unit test for the property 'MusicFormat'
        }
        /// <summary>
        /// Test the property 'MusicReleaseDate'
        /// </summary>
        [Test]
        public void MusicReleaseDateTest()
        {
            // TODO unit test for the property 'MusicReleaseDate'
        }
        /// <summary>
        /// Test the property 'OmitFromFeed'
        /// </summary>
        [Test]
        public void OmitFromFeedTest()
        {
            // TODO unit test for the property 'OmitFromFeed'
        }
        /// <summary>
        /// Test the property 'ProductType'
        /// </summary>
        [Test]
        public void ProductTypeTest()
        {
            // TODO unit test for the property 'ProductType'
        }
        /// <summary>
        /// Test the property 'PromotionId1'
        /// </summary>
        [Test]
        public void PromotionId1Test()
        {
            // TODO unit test for the property 'PromotionId1'
        }
        /// <summary>
        /// Test the property 'PromotionId10'
        /// </summary>
        [Test]
        public void PromotionId10Test()
        {
            // TODO unit test for the property 'PromotionId10'
        }
        /// <summary>
        /// Test the property 'PromotionId2'
        /// </summary>
        [Test]
        public void PromotionId2Test()
        {
            // TODO unit test for the property 'PromotionId2'
        }
        /// <summary>
        /// Test the property 'PromotionId3'
        /// </summary>
        [Test]
        public void PromotionId3Test()
        {
            // TODO unit test for the property 'PromotionId3'
        }
        /// <summary>
        /// Test the property 'PromotionId4'
        /// </summary>
        [Test]
        public void PromotionId4Test()
        {
            // TODO unit test for the property 'PromotionId4'
        }
        /// <summary>
        /// Test the property 'PromotionId5'
        /// </summary>
        [Test]
        public void PromotionId5Test()
        {
            // TODO unit test for the property 'PromotionId5'
        }
        /// <summary>
        /// Test the property 'PromotionId6'
        /// </summary>
        [Test]
        public void PromotionId6Test()
        {
            // TODO unit test for the property 'PromotionId6'
        }
        /// <summary>
        /// Test the property 'PromotionId7'
        /// </summary>
        [Test]
        public void PromotionId7Test()
        {
            // TODO unit test for the property 'PromotionId7'
        }
        /// <summary>
        /// Test the property 'PromotionId8'
        /// </summary>
        [Test]
        public void PromotionId8Test()
        {
            // TODO unit test for the property 'PromotionId8'
        }
        /// <summary>
        /// Test the property 'PromotionId9'
        /// </summary>
        [Test]
        public void PromotionId9Test()
        {
            // TODO unit test for the property 'PromotionId9'
        }
        /// <summary>
        /// Test the property 'SearchDts'
        /// </summary>
        [Test]
        public void SearchDtsTest()
        {
            // TODO unit test for the property 'SearchDts'
        }
        /// <summary>
        /// Test the property 'SearchLowestPrice'
        /// </summary>
        [Test]
        public void SearchLowestPriceTest()
        {
            // TODO unit test for the property 'SearchLowestPrice'
        }
        /// <summary>
        /// Test the property 'SearchLowestUrl'
        /// </summary>
        [Test]
        public void SearchLowestUrlTest()
        {
            // TODO unit test for the property 'SearchLowestUrl'
        }
        /// <summary>
        /// Test the property 'SearchPosition'
        /// </summary>
        [Test]
        public void SearchPositionTest()
        {
            // TODO unit test for the property 'SearchPosition'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'VideoDirector'
        /// </summary>
        [Test]
        public void VideoDirectorTest()
        {
            // TODO unit test for the property 'VideoDirector'
        }
        /// <summary>
        /// Test the property 'VideoFormat'
        /// </summary>
        [Test]
        public void VideoFormatTest()
        {
            // TODO unit test for the property 'VideoFormat'
        }
        /// <summary>
        /// Test the property 'VideoRating'
        /// </summary>
        [Test]
        public void VideoRatingTest()
        {
            // TODO unit test for the property 'VideoRating'
        }
        /// <summary>
        /// Test the property 'VideoReleaseDate'
        /// </summary>
        [Test]
        public void VideoReleaseDateTest()
        {
            // TODO unit test for the property 'VideoReleaseDate'
        }
        /// <summary>
        /// Test the property 'VideoStarring'
        /// </summary>
        [Test]
        public void VideoStarringTest()
        {
            // TODO unit test for the property 'VideoStarring'
        }

    }

}
