/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing ItemVariantItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemVariantItemTests
    {
        // TODO uncomment below to declare an instance variable for ItemVariantItem
        //private ItemVariantItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemVariantItem
            //instance = new ItemVariantItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemVariantItem
        /// </summary>
        [Test]
        public void ItemVariantItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemVariantItem
            //Assert.IsInstanceOfType<ItemVariantItem> (instance, "variable 'instance' is a ItemVariantItem");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'MerchantItemMultimediaOid'
        /// </summary>
        [Test]
        public void MerchantItemMultimediaOidTest()
        {
            // TODO unit test for the property 'MerchantItemMultimediaOid'
        }
        /// <summary>
        /// Test the property 'VariantMerchantItemId'
        /// </summary>
        [Test]
        public void VariantMerchantItemIdTest()
        {
            // TODO unit test for the property 'VariantMerchantItemId'
        }
        /// <summary>
        /// Test the property 'VariantMerchantItemOid'
        /// </summary>
        [Test]
        public void VariantMerchantItemOidTest()
        {
            // TODO unit test for the property 'VariantMerchantItemOid'
        }
        /// <summary>
        /// Test the property 'VariationOptions'
        /// </summary>
        [Test]
        public void VariationOptionsTest()
        {
            // TODO unit test for the property 'VariationOptions'
        }
        /// <summary>
        /// Test the property 'Variations'
        /// </summary>
        [Test]
        public void VariationsTest()
        {
            // TODO unit test for the property 'Variations'
        }

    }

}
