/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing OrderItemEdiIdentification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderItemEdiIdentificationTests
    {
        // TODO uncomment below to declare an instance variable for OrderItemEdiIdentification
        //private OrderItemEdiIdentification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderItemEdiIdentification
            //instance = new OrderItemEdiIdentification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderItemEdiIdentification
        /// </summary>
        [Test]
        public void OrderItemEdiIdentificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderItemEdiIdentification
            //Assert.IsInstanceOfType<OrderItemEdiIdentification> (instance, "variable 'instance' is a OrderItemEdiIdentification");
        }


        /// <summary>
        /// Test the property 'Identification'
        /// </summary>
        [Test]
        public void IdentificationTest()
        {
            // TODO unit test for the property 'Identification'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
