/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing OrderCoupon
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderCouponTests
    {
        // TODO uncomment below to declare an instance variable for OrderCoupon
        //private OrderCoupon instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderCoupon
            //instance = new OrderCoupon();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderCoupon
        /// </summary>
        [Test]
        public void OrderCouponInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderCoupon
            //Assert.IsInstanceOfType<OrderCoupon> (instance, "variable 'instance' is a OrderCoupon");
        }


        /// <summary>
        /// Test the property 'AccountingCode'
        /// </summary>
        [Test]
        public void AccountingCodeTest()
        {
            // TODO unit test for the property 'AccountingCode'
        }
        /// <summary>
        /// Test the property 'BaseCouponCode'
        /// </summary>
        [Test]
        public void BaseCouponCodeTest()
        {
            // TODO unit test for the property 'BaseCouponCode'
        }
        /// <summary>
        /// Test the property 'CouponCode'
        /// </summary>
        [Test]
        public void CouponCodeTest()
        {
            // TODO unit test for the property 'CouponCode'
        }

    }

}
