/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing OrderItemOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderItemOptionTests
    {
        // TODO uncomment below to declare an instance variable for OrderItemOption
        //private OrderItemOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderItemOption
            //instance = new OrderItemOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderItemOption
        /// </summary>
        [Test]
        public void OrderItemOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderItemOption
            //Assert.IsInstanceOfType<OrderItemOption> (instance, "variable 'instance' is a OrderItemOption");
        }


        /// <summary>
        /// Test the property 'AdditionalDimensionApplication'
        /// </summary>
        [Test]
        public void AdditionalDimensionApplicationTest()
        {
            // TODO unit test for the property 'AdditionalDimensionApplication'
        }
        /// <summary>
        /// Test the property 'CostChange'
        /// </summary>
        [Test]
        public void CostChangeTest()
        {
            // TODO unit test for the property 'CostChange'
        }
        /// <summary>
        /// Test the property 'FileAttachment'
        /// </summary>
        [Test]
        public void FileAttachmentTest()
        {
            // TODO unit test for the property 'FileAttachment'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Hidden'
        /// </summary>
        [Test]
        public void HiddenTest()
        {
            // TODO unit test for the property 'Hidden'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'OneTimeFee'
        /// </summary>
        [Test]
        public void OneTimeFeeTest()
        {
            // TODO unit test for the property 'OneTimeFee'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'WeightChange'
        /// </summary>
        [Test]
        public void WeightChangeTest()
        {
            // TODO unit test for the property 'WeightChange'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

    }

}
