/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing OrderShipping
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderShippingTests
    {
        // TODO uncomment below to declare an instance variable for OrderShipping
        //private OrderShipping instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderShipping
            //instance = new OrderShipping();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderShipping
        /// </summary>
        [Test]
        public void OrderShippingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderShipping
            //Assert.IsInstanceOfType<OrderShipping> (instance, "variable 'instance' is a OrderShipping");
        }


        /// <summary>
        /// Test the property 'Address1'
        /// </summary>
        [Test]
        public void Address1Test()
        {
            // TODO unit test for the property 'Address1'
        }
        /// <summary>
        /// Test the property 'Address2'
        /// </summary>
        [Test]
        public void Address2Test()
        {
            // TODO unit test for the property 'Address2'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'DayPhone'
        /// </summary>
        [Test]
        public void DayPhoneTest()
        {
            // TODO unit test for the property 'DayPhone'
        }
        /// <summary>
        /// Test the property 'DeliveryDate'
        /// </summary>
        [Test]
        public void DeliveryDateTest()
        {
            // TODO unit test for the property 'DeliveryDate'
        }
        /// <summary>
        /// Test the property 'EveningPhone'
        /// </summary>
        [Test]
        public void EveningPhoneTest()
        {
            // TODO unit test for the property 'EveningPhone'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'LiftGate'
        /// </summary>
        [Test]
        public void LiftGateTest()
        {
            // TODO unit test for the property 'LiftGate'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'Rma'
        /// </summary>
        [Test]
        public void RmaTest()
        {
            // TODO unit test for the property 'Rma'
        }
        /// <summary>
        /// Test the property 'ShipOnDate'
        /// </summary>
        [Test]
        public void ShipOnDateTest()
        {
            // TODO unit test for the property 'ShipOnDate'
        }
        /// <summary>
        /// Test the property 'ShipToResidential'
        /// </summary>
        [Test]
        public void ShipToResidentialTest()
        {
            // TODO unit test for the property 'ShipToResidential'
        }
        /// <summary>
        /// Test the property 'Shipping3rdPartyAccountNumber'
        /// </summary>
        [Test]
        public void Shipping3rdPartyAccountNumberTest()
        {
            // TODO unit test for the property 'Shipping3rdPartyAccountNumber'
        }
        /// <summary>
        /// Test the property 'ShippingDate'
        /// </summary>
        [Test]
        public void ShippingDateTest()
        {
            // TODO unit test for the property 'ShippingDate'
        }
        /// <summary>
        /// Test the property 'ShippingDepartmentStatus'
        /// </summary>
        [Test]
        public void ShippingDepartmentStatusTest()
        {
            // TODO unit test for the property 'ShippingDepartmentStatus'
        }
        /// <summary>
        /// Test the property 'ShippingMethod'
        /// </summary>
        [Test]
        public void ShippingMethodTest()
        {
            // TODO unit test for the property 'ShippingMethod'
        }
        /// <summary>
        /// Test the property 'ShippingMethodAccountingCode'
        /// </summary>
        [Test]
        public void ShippingMethodAccountingCodeTest()
        {
            // TODO unit test for the property 'ShippingMethodAccountingCode'
        }
        /// <summary>
        /// Test the property 'SpecialInstructions'
        /// </summary>
        [Test]
        public void SpecialInstructionsTest()
        {
            // TODO unit test for the property 'SpecialInstructions'
        }
        /// <summary>
        /// Test the property 'StateRegion'
        /// </summary>
        [Test]
        public void StateRegionTest()
        {
            // TODO unit test for the property 'StateRegion'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'TrackingNumbers'
        /// </summary>
        [Test]
        public void TrackingNumbersTest()
        {
            // TODO unit test for the property 'TrackingNumbers'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

    }

}
