/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing WebhookSampleRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebhookSampleRequestTests
    {
        // TODO uncomment below to declare an instance variable for WebhookSampleRequest
        //private WebhookSampleRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookSampleRequest
            //instance = new WebhookSampleRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookSampleRequest
        /// </summary>
        [Test]
        public void WebhookSampleRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookSampleRequest
            //Assert.IsInstanceOfType<WebhookSampleRequest> (instance, "variable 'instance' is a WebhookSampleRequest");
        }


        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Test]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }
        /// <summary>
        /// Test the property 'RequestHeaders'
        /// </summary>
        [Test]
        public void RequestHeadersTest()
        {
            // TODO unit test for the property 'RequestHeaders'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

    }

}
